name: Create GitHub Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper tagging
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## Changes in this Release
          
          See [CHANGELOG.md](./CHANGELOG.md) for detailed information about this release.
          
          ### Quick Start
          ```bash
          npm install
          npm run dev
          ```
          
          ### Deployment
          This release is ready for deployment to production.
        draft: false
        prerelease: false
